import { FormEvent,useEffect,useState } from 'react';
import { vehiclesApi,maintenanceApi,fuelApi } from '../lib/api';
import type { Vehicle,Maintenance,FuelLog } from '../types';

const blank={code:'',registration:'',brand:'',model:'',year:new Date().getFullYear(),type:'Camion caisse',capacityTons:0,mileageKm:0,status:'Disponible',location:'Kolwezi',insuranceExpiry:'',inspectionExpiry:'',nextServiceKm:0,fuelType:'Diesel'};
export default function Fleet(){
 const[vehicles,setVehicles]=useState<Vehicle[]>([]),[maint,setMaint]=useState<Maintenance[]>([]),[fuel,setFuel]=useState<FuelLog[]>([]);
 const[open,setOpen]=useState(false),[editing,setEditing]=useState<Vehicle|null>(null),[form,setForm]=useState<any>(blank),[selected,setSelected]=useState<Vehicle|null>(null),[tab,setTab]=useState('fleet');
 const load=async()=>{const[v,m,f]=await Promise.all([vehiclesApi.list(),maintenanceApi.list(),fuelApi.list()]);setVehicles(v);setMaint(m);setFuel(f)};
 useEffect(()=>{void load()},[]);
 const save=async(e:FormEvent)=>{e.preventDefault();editing?await vehiclesApi.update(editing.id,form):await vehiclesApi.create(form);setOpen(false);setEditing(null);setForm(blank);await load()};
 const edit=(v:Vehicle)=>{setEditing(v);setForm({...v});setOpen(true)};
 const remove=async(id:string)=>{if(confirm('Supprimer ce véhicule ?'))try{await vehiclesApi.remove(id);await load()}catch{alert('Véhicule lié à une mission.')}};
 const totalFuel=fuel.reduce((a,x)=>a+x.totalCost,0), totalMaint=maint.reduce((a,x)=>a+x.cost,0);
 return <><div className="top"><div><h1>Fleet Management</h1><p>Véhicules, maintenance, carburant et documents</p></div><button className="btn" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}>＋ Ajouter véhicule</button></div>
 <div className="grid"><div className="card"><small>Flotte totale</small><div className="value">{vehicles.length}</div></div><div className="card"><small>Disponibles</small><div className="value">{vehicles.filter(v=>v.status==='Disponible').length}</div></div><div className="card"><small>Maintenance</small><div className="value">{vehicles.filter(v=>v.status==='Maintenance').length}</div></div><div className="card"><small>Coûts flotte</small><div className="value">{(totalFuel+totalMaint).toLocaleString()} USD</div></div></div>
 <div className="tabs-line"><button className={tab==='fleet'?'active':''} onClick={()=>setTab('fleet')}>Flotte</button><button className={tab==='maintenance'?'active':''} onClick={()=>setTab('maintenance')}>Maintenance</button><button className={tab==='fuel'?'active':''} onClick={()=>setTab('fuel')}>Carburant</button></div>
 {tab==='fleet'&&<div className="fleet-grid">{vehicles.map(v=><div className="vehicle-card" key={v.id}><div className="vehicle-head"><div><small>{v.code}</small><h3>{v.brand} {v.model}</h3><p>{v.registration} • {v.type}</p></div><span className="badge">{v.status}</span></div><div className="vehicle-metrics"><div><small>Kilométrage</small><strong>{v.mileageKm.toLocaleString()} km</strong></div><div><small>Capacité</small><strong>{v.capacityTons} t</strong></div><div><small>Assurance</small><strong>{v.insuranceExpiry||'—'}</strong></div><div><small>Entretien</small><strong>{v.nextServiceKm?.toLocaleString()||'—'} km</strong></div></div><div><button className="mini" onClick={()=>setSelected(v)}>Voir</button> <button className="mini" onClick={()=>edit(v)}>Modifier</button> <button className="mini danger" onClick={()=>remove(v.id)}>Supprimer</button></div></div>)}</div>}
 {tab==='maintenance'&&<MaintenancePanel vehicles={vehicles} items={maint} reload={load}/>}
 {tab==='fuel'&&<FuelPanel vehicles={vehicles} items={fuel} reload={load}/>}
 {selected&&<div className="overlay"><div className="modal-form wide"><h2>{selected.code} — {selected.brand} {selected.model}</h2><div className="detail-grid"><p><strong>Statut :</strong> {selected.status}</p><p><strong>Localisation :</strong> {selected.location}</p><p><strong>Immatriculation :</strong> {selected.registration}</p><p><strong>Année :</strong> {selected.year}</p><p><strong>Carburant :</strong> {selected.fuelType}</p><p><strong>Contrôle :</strong> {selected.inspectionExpiry}</p></div><button className="btn" onClick={()=>setSelected(null)}>Fermer</button></div></div>}
 {open&&<div className="overlay"><form className="modal-form" onSubmit={save}><h2>{editing?'Modifier le véhicule':'Nouveau véhicule'}</h2>{Object.entries({code:'Code MSS',registration:'Immatriculation',brand:'Marque',model:'Modèle',year:'Année',capacityTons:'Capacité tonnes',mileageKm:'Kilométrage',location:'Localisation',insuranceExpiry:'Expiration assurance',inspectionExpiry:'Expiration contrôle',nextServiceKm:'Prochain entretien km'}).map(([k,l])=><label key={k}>{l}<input type={k.includes('Expiry')?'date':['year','capacityTons','mileageKm','nextServiceKm'].includes(k)?'number':'text'} value={form[k]??''} onChange={e=>setForm({...form,[k]:['year','capacityTons','mileageKm','nextServiceKm'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Camion caisse</option><option>Camion frigorifique</option><option>Camion plateau</option><option>Minibus</option><option>Bus</option><option>Pick-up 4x4</option></select></label><label>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Disponible</option><option>En mission</option><option>Maintenance</option><option>Hors service</option></select></label><label>Carburant<select value={form.fuelType} onChange={e=>setForm({...form,fuelType:e.target.value})}><option>Diesel</option><option>Essence</option></select></label><div className="modal-actions"><button type="button" className="mini" onClick={()=>setOpen(false)}>Annuler</button><button className="btn">Enregistrer</button></div></form></div>}</>
}

function MaintenancePanel({vehicles,items,reload}:{vehicles:Vehicle[],items:Maintenance[],reload:()=>Promise<void>}){
 const[open,setOpen]=useState(false),[form,setForm]=useState<any>({vehicleId:'',serviceDate:new Date().toISOString().slice(0,10),type:'Préventive',description:'',garage:'Atelier MSS',cost:0,nextDate:'',nextMileage:0,status:'Planifiée'});
 const save=async(e:FormEvent)=>{e.preventDefault();await maintenanceApi.create(form);setOpen(false);await reload()};
 const cycle=async(x:Maintenance)=>{const flow=['Planifiée','En cours','Clôturée'];await maintenanceApi.update(x.id,{status:flow[(flow.indexOf(x.status)+1)%flow.length]});await reload()};
 return <><button className="btn" onClick={()=>setOpen(true)}>＋ Intervention</button><div className="card"><table className="table"><thead><tr><th>N°</th><th>Véhicule</th><th>Date</th><th>Type</th><th>Coût</th><th>Prochaine échéance</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.vehicle?.code} {x.vehicle?.model}</td><td>{x.serviceDate}</td><td>{x.type}</td><td>{x.cost} USD</td><td>{x.nextDate||'—'} / {x.nextMileage||0} km</td><td><span className="badge">{x.status}</span></td><td><button className="mini" onClick={()=>cycle(x)}>Changer statut</button></td></tr>)}</tbody></table></div>{open&&<div className="overlay"><form className="modal-form" onSubmit={save}><h2>Intervention</h2><label>Véhicule<select required value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})}><option value="">Sélectionner</option>{vehicles.map(v=><option value={v.id}>{v.code} — {v.model}</option>)}</select></label>{['serviceDate','description','garage','cost','nextDate','nextMileage'].map(k=><label key={k}>{k}<input type={k.includes('Date')?'date':['cost','nextMileage'].includes(k)?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:['cost','nextMileage'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Préventive</option><option>Corrective</option><option>Vidange</option><option>Pneus</option><option>Freinage</option></select></label><label>Statut<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Planifiée</option><option>En cours</option><option>Clôturée</option></select></label><div className="modal-actions"><button type="button" className="mini" onClick={()=>setOpen(false)}>Annuler</button><button className="btn">Enregistrer</button></div></form></div>}</>
}
function FuelPanel({vehicles,items,reload}:{vehicles:Vehicle[],items:FuelLog[],reload:()=>Promise<void>}){
 const[open,setOpen]=useState(false),[form,setForm]=useState<any>({vehicleId:'',fuelDate:new Date().toISOString().slice(0,10),liters:0,pricePerLiter:0,mileage:0,station:'',reference:''});
 const save=async(e:FormEvent)=>{e.preventDefault();await fuelApi.create(form);setOpen(false);await reload()};
 return <><button className="btn" onClick={()=>setOpen(true)}>＋ Ravitaillement</button><div className="card"><table className="table"><thead><tr><th>N°</th><th>Véhicule</th><th>Date</th><th>Litres</th><th>Coût</th><th>Kilométrage</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.number}</td><td>{x.vehicle?.code} {x.vehicle?.model}</td><td>{x.fuelDate}</td><td>{x.liters} L</td><td>{x.totalCost.toFixed(2)} USD</td><td>{x.mileage.toLocaleString()} km</td></tr>)}</tbody></table></div>{open&&<div className="overlay"><form className="modal-form" onSubmit={save}><h2>Carburant</h2><label>Véhicule<select required value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})}><option value="">Sélectionner</option>{vehicles.map(v=><option value={v.id}>{v.code} — {v.model}</option>)}</select></label>{['fuelDate','liters','pricePerLiter','mileage','station','reference'].map(k=><label key={k}>{k}<input type={k==='fuelDate'?'date':['liters','pricePerLiter','mileage'].includes(k)?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:['liters','pricePerLiter','mileage'].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<div className="modal-actions"><button type="button" className="mini" onClick={()=>setOpen(false)}>Annuler</button><button className="btn">Enregistrer</button></div></form></div>}</>
}
